export enum ActivityType {
  SIGN_UP = 'SIGN_UP', // parent
  SIGN_IN = 'SIGN_IN', // parent
  SIGN_OUT = 'SIGN_OUT', // parent
  UPDATE_PASSWORD = 'UPDATE_PASSWORD', // parent
  DELETE_ACCOUNT = 'DELETE_ACCOUNT', // parent
  UPDATE_ACCOUNT = 'UPDATE_ACCOUNT', // parent
  UPDATE_USER = 'UPDATE_USER', // parent
  TEST = 'TEST', // interne/dev, system
  GET_SUBSCRIPTION_BY_USER = 'GET_SUBSCRIPTION_BY_USER', // admin
  START_TRIAL = 'START_TRIAL', // parent
  CANCEL_TRIAL = 'CANCEL_TRIAL', // parent
  SUBSCRIBING = 'SUBSCRIBING', // parent
  GET_SUBSCRIBE_STATUS = 'GET_SUBSCRIBE_STATUS', // admin
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED', // parent
  SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED', // parent
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED', // parent
  SUBSCRIPTION_DELETED = 'SUBSCRIPTION_DELETED', // parent
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED', // parent
  PAYMENT_FAILED = 'PAYMENT_FAILED', // parent
  SUBSCRIPTION_ERROR = 'SUBSCRIPTION_ERROR', // parent
  PAYMENT_RETRY = 'PAYMENT_RETRY', // parent
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED', // parent
  TRIAL_ENDING_NOTIFICATION = 'TRIAL_ENDING_NOTIFICATION', // parent, system
  CALL_WEBHOOK = 'CALL_WEBHOOK', // interne/dev, system
  CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION', // parent
  ASSIGN_ROLE = 'ASSIGN_ROLE', // admin
  CHECK_PERMISSION = 'CHECK_PERMISSION', // admin
  GET_CUSTOM_ROLES = 'GET_CUSTOM_ROLES', // admin
  CREATE_ROLE = 'CREATE_ROLE', // admin
  CREATE_PERMISSION = 'CREATE_PERMISSION', // admin
  UPDATE_ROLE = 'UPDATE_ROLE', // admin
  DELETE_ROLE = 'DELETE_ROLE', // admin
  GET_ROLE = 'GET_ROLE', // admin
  CHANGE_SUBSCRIPTION_PLAN = 'CHANGE_SUBSCRIPTION_PLAN', // admin
  GET_CHILDREN = 'GET_CHILDREN', // parent
  GET_CHILD = 'GET_CHILD', // parent
  CREATE_CHILD = 'CREATE_CHILD', // parent
  UPDATE_CHILD = 'UPDATE_CHILD', // parent
  DELETE_CHILD = 'DELETE_CHILD', // parent
  UPDATE_CHILD_AVATAR = 'UPDATE_CHILD_AVATAR', // parent
  GET_AVATAR = 'GET_AVATAR', // parent
  CREATE_AVATAR = 'CREATE_AVATAR', // parent
  DELETE_AVATAR = 'DELETE_AVATAR', // parent
  UPDATE_AVATAR = 'UPDATE_AVATAR', // parent
  CREATE_MODULE = 'CREATE_MODULE', // admin
  LIST_MODULES = 'LIST_MODULES', // admin
  GET_MODULE = 'GET_MODULE', // admin
  UPDATE_MODULE = 'UPDATE_MODULE', // admin
  ACTIVE_MODULE = 'ACTIVE_MODULE', // admin
  DESACTIVE_MODULE = 'DESACTIVE_MODULE', // admin
  DELETE_MODULE = 'DELETE_MODULE', // admin
  CREATE_LESSON = 'CREATE_LESSON', // admin
  LIST_LESSONS = 'LIST_LESSONS', // admin
  GET_LESSON = 'GET_LESSON', // admin
  UPDATE_LESSON = 'UPDATE_LESSON', // admin
  DELETE_LESSON = 'DELETE_LESSON', // admin
  CREATE_GAME = 'CREATE_GAME', // admin
  LIST_GAMES = 'LIST_GAMES', // admin
  GET_GAME = 'GET_GAME', // admin
  UPDATE_GAME = 'UPDATE_GAME', // admin
  DELETE_GAME = 'DELETE_GAME', // admin
  ADD_GAME_PREREQUISITE = 'ADD_GAME_PREREQUISITE', // admin
  REMOVE_GAME_PREREQUISITE = 'REMOVE_GAME_PREREQUISITE', // admin
  START_GAME_SESSION = 'START_GAME_SESSION', // enfant
  COMPLETE_GAME_SESSION = 'COMPLETE_GAME_SESSION', // enfant
  GET_GAME_SESSION = 'GET_GAME_SESSION', // enfant
  LIST_GAME_SESSIONS = 'LIST_GAME_SESSIONS', // enfant
  ABANDON_GAME_SESSION = 'ABANDON_GAME_SESSION', // enfant
  GET_TRIAL_CONFIG = 'GET_TRIAL_CONFIG', // admin
  UPDATE_TRIAL_CONFIG = 'UPDATE_TRIAL_CONFIG', // admin
  DELETE_GAME_FILE = 'DELETE_GAME_FILE', // admin
  CREATE_PLAN = 'CREATE_PLAN', // admin
  READ_PLAN = 'READ_PLAN', // admin
  UPDATE_PLAN = 'UPDATE_PLAN', // admin
  DELETE_PLAN = 'DELETE_PLAN', // admin
  REORDER_MODULES = 'REORDER_MODULES', // admin
  REORDER_LESSON_GAMES = 'REORDER_LESSON_GAMES', // admin
  GET_SYSTEM_CONFIG = 'GET_SYSTEM_CONFIG',
  UPDATE_SYSTEM_CONFIG = 'UPDATE_SYSTEM_CONFIG',
  LIST_AVATARS = 'LIST_AVATARS',
  LIST_SUBSCRIPTION_PLAN = 'LIST_SUBSCRIPTION_PLAN',
  LIST_PARENTS = 'LIST_PARENTS',
  ACTIVATE_MODULE = 'ACTIVATE_MODULE',
  DEACTIVATE_MODULE = 'DEACTIVATE_MODULE',
  LIST_USERS = 'LIST_USERS',
  CREATE_USER = 'CREATE_USER',
  GET_PARENT = 'GET_PARENT',
  LIST_ROLES = 'LIST_ROLES',
  GET_STATS = 'GET_STATS'
}

export const ActivityActionType = {
  SIGN_UP: 'CREATE',
  SIGN_IN: 'LOGIN',
  SIGN_OUT: 'LOGOUT',
  DELETE_ACCOUNT: 'DELETE',
  UPDATE_USER: 'UPDATE',
  START_TRIAL: 'CREATE',
  CANCEL_TRIAL: 'CANCEL',
  SUBSCRIBING: 'SUBSCRIBE',
  SUBSCRIPTION_DELETED: 'DELETE',
  CANCEL_SUBSCRIPTION: 'UNSUBSCRIBE',
  CREATE_ROLE: 'CREATE',
  CREATE_PERMISSION: 'CREATE',
  UPDATE_ROLE: 'UPDATE',
  DELETE_ROLE: 'DELETE',
  GET_ROLE: 'READ',
  CHANGE_SUBSCRIPTION_PLAN: 'CHANGE',
  GET_CHILD: 'READ',
  CREATE_CHILD: 'CREATE',
  UPDATE_CHILD: 'UPDATE',
  DELETE_CHILD: 'DELETE',
  UPDATE_CHILD_AVATAR: 'UPDATE',
  CREATE_AVATAR: 'CREATE',
  DELETE_AVATAR: 'DELETE',
  UPDATE_AVATAR: 'UPDATE',
  CREATE_MODULE: 'CREATE',
  LIST_MODULES: 'READ',
  GET_MODULE: 'READ',
  UPDATE_MODULE: 'UPDATE',
  ACTIVATE_MODULE: 'ACTIVATE',
  DEACTIVATE_MODULE: 'DEACTIVATE',
  DELETE_MODULE: 'DELETE',
  CREATE_LESSON: 'CREATE',
  LIST_LESSONS: 'READ',
  UPDATE_LESSON: 'UPDATE',
  DELETE_LESSON: 'DELETE',
  CREATE_GAME: 'CREATE',
  LIST_GAMES: 'READ',
  UPDATE_GAME: 'UPDATE',
  DELETE_GAME: 'DELETE',
  UPDATE_TRIAL_CONFIG: 'UPDATE',
  CREATE_PLAN: 'CREATE',
  READ_PLAN: 'READ',
  UPDATE_PLAN: 'UPDATE',
  DELETE_PLAN: 'DELETE',
  REORDER_MODULES: 'REORDER',
  REORDER_LESSON_GAMES: 'REORDER',
  LIST_AVATARS: 'READ',
  LIST_SUBSCRIPTION_PLAN: 'READ',
  LIST_PARENTS: 'READ',
  LIST_USERS: 'READ',
  CREATE_USER: 'CREATE',
  GET_PARENT: 'READ',
  LIST_ROLES: 'READ',
  GET_STATS: 'READ'
}
